export const frameworks = {
    JavaScript: ["React", "Vue.js", "Angular", "Node.js", "Express.js"],
    Python: ["Django", "Flask", "FastAPI", "Pyramid"],
    Java: ["Spring", "Hibernate", "Struts", "JSF"],
    "C++": ["Qt", "Boost", "POCO"],
    "C#": ["ASP.NET", "Blazor", "Unity"],
    PHP: ["Laravel", "Symfony", "CodeIgniter", "Zend"],
    Swift: ["SwiftUI", "Vapor"],
    Go: ["Gin", "Echo", "Fiber", "Beego"],
    Kotlin: ["Ktor", "Jetpack Compose"],
    Rust: ["Rocket", "Actix", "Warp"],
    Ruby: ["Ruby on Rails", "Sinatra", "Hanami"],
    TypeScript: ["NestJS", "Deno", "ts-morph"],
    Dart: ["Flutter", "Aqueduct"],
    Scala: ["Play Framework", "Akka", "Lift"],
    Perl: ["Mojolicious", "Dancer", "Catalyst"],
    Lua: ["Lapis", "OpenResty"],
    Haskell: ["Yesod", "Snap", "Scotty"],
    "Objective-C": ["Cocoa", "GNUStep"]
};
